### ISSUE TITLE
Leading zeros not standard

### ISSUE THREAD

**Issue by dcousens** [dcousens/base-x#2]
@subliminator, you mentioned this in #1:

> On a related note, I believe the way the leading zeroes are encoded is somewhat bitcoin style (doge, ripple, stellar, etc) address specific. Imagine if you used hex alphabet 0-F for example. You'd be forgiven for expecting each leading 0 to decode to 4 bits, but instead it would decode to a full byte.

I don't think that is true,  do you have some test data to show case this?

**Comment by sublimator** [comment]
I will look into it more, but just by casual reading of that snippet before, it seemed like it was zooming from the left most character of the input string, and decoding a byte for each. 

Will get back to you, hopefully in the form of pull request / test case :)

**Comment by sublimator** [comment]
^ decoding a byte for each leading zero ( the "1" it was hardcoded to)

**Comment by sublimator** [comment]
Confirmed. The leading zeroes behaviour seems to be to encode any leading zeroes in the byte array as the first character in the alphabet, and decode correspondingly, by taking any leading zero characters and decoding them directly to a byte, regardless of the base.

**Comment by sublimator** [comment]
I guess the question is, if there is a more generic algorithm for encoding the leading zeroes that could handle non base58 AND base58 while passing existing tests and maintaining performance ?

**Comment by sublimator** [comment]
Hrmm, I think not

**Comment by dcousens** [comment]
@sublimator ah, did you mean how this currently fails: https://github.com/dcousens/base-x/commit/4967e695a65112c6612357eaed37946f38284122 ?

**Comment by sublimator** [comment]
Yes, I just hack an uncompressed parameter into the constructor and did some Math.log(256) / Math.log(BASE) silliness and it passes some base16/base2 tests.

**Comment by sublimator** [comment]
But I guess that's not gonna work for some of these base encodings that use padding.

**Comment by sublimator** [comment]
https://github.com/sublimator/base-x/tree/canonical

The silliness mentioned earlier ^

**Comment by sublimator** [comment]
#8

**Comment by dcousens** [comment]
Going to close this, as it is now well documented in the README.
