### ISSUE TITLE
bs58 perf/bugfixes

### ISSUE THREAD

**Issue by sublimator** [dcousens/base-x#6]
I noticed that the repo this was forked from contains this: 
https://github.com/cryptocoinjs/bs58/commit/01d308fd6e5f7bdc63554047ccc3c028d4ce2fc2

Could bs58 build off this module?

**Comment by dcousens** [comment]
Sure, go ahead and make the PR :),  not sure how it was missed to be honest.

**Comment by jprichardson** [comment]
> Could bs58 build off this module?

I'm open to this discussion :p

**Comment by sublimator** [comment]
> I'm open to this discussion :p

Nice, I think it would make a certain amount of sense for one to build off the other :)

**Comment by sublimator** [comment]
What's a good approach to do that? I'm thinking:

1.  Just copy paste the current bs58.js over the top of index.js
2.  Manually reapply generalisation
3.  Fix up any `standard` (code styling) issues
4.  Commit as one change.

?

For the moment #7

**Comment by sublimator** [comment]
A pull request to resync to the parent if desired: #9
